sign_in:
  description: Sign the controller in to a HEOS account.
  fields:
    username:
      description: The username or email of the HEOS account. [Required]
      example: "example@example.com"
    password:
      description: The password of the HEOS account. [Required]
      example: "password"

sign_out:
  description: Sign the controller out of the HEOS account.

join:
  description: Group players together as a HEOS group.
  fields:
    leader:
      description: The HEOS group leader. [Required]
      example: 'media_player.heos_player1'
    entity_id:
      description: Additional media players to be included in the group. [Required]
      example: 'media_player.heos_player2'

unjoin:
  description: Unjoin the player from a group.
  fields:
    entity_id:
      description: Name(s) of entities that will be unjoined from their group.
      example: 'media_player.heos_player2'
